//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int Id { get; set; }
        public int IdDeporte { get; set; }
        public int IdProfesor { get; set; }
        public string Nombre { get; set; }
        public string Observacion { get; set; }
        public int Duracion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
    
        public virtual Deporte Deporte { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
