//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolancoEntities : DbContext
    {
        public PolancoEntities()
            : base("name=PolancoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Profesor> Profesors { get; set; }
        public DbSet<TipoArea> TipoAreas { get; set; }
        public DbSet<TipoAsociado> TipoAsociadoes { get; set; }
        public DbSet<Area> Areas { get; set; }
        public DbSet<Deporte> Deportes { get; set; }
        public DbSet<Curso> Cursoes { get; set; }
    }
}
