//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software.Datos
{
    using System;
    using System.Collections.Generic;

    public partial class TipoArea
    {
        public Int32 Codigo { get; set; }
        public String Descripcion { get; set; }

        public TipoArea()
        {
        }

        public TipoArea(Int32 codigo, String descripcion)
        {
            this.Codigo = codigo;
            this.Descripcion = descripcion;
        }
    }
}
